# Service

apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  selector:
    app: company
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
      - name: company
        image: spaceavocado34/company-service:1.0-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://company-database-service:5432/company-service"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: doc-gen-secrets
              key: postgres_datasource_password