# App
spring.application.name=api-gateway

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Server
server.port=8080

# Jwt
token.secret.key=${TOKEN_SECRET_KEY}

# Client
cors.client.host=${CORS_CLIENT_HOST}
cors.client.port=${CORS_CLIENT_PORT}

# Logging
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE