# App
spring.application.name=document-service

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:development}

# Datasource
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Message queue
spring.artemis.mode=native
spring.artemis.broker-url=${SPRING_ARTEMIS_URL}
spring.artemis.user=${SPRING_ARTEMIS_USER}
spring.artemis.password=${SPRING_ARTEMIS_PASSWORD}
spring.jms.template.default-destination=default-queue

# Server
server.servlet.session.cookie.same-site=strict