# Service

apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  selector:
    app: document
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: document
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document
  template:
    metadata:
      labels:
        app: document
    spec:
      containers:
      - name: document
        image: spaceavocado34/document-service:1.0-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://document-database-service:27017/document-service"